package luke.nai.project.astar.gui;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author LukaszDrapala
 */
public class GamePanel extends javax.swing.JPanel {

    private Context context;
    private GameModel gameModel;
    private JButton[][] buttons;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        gameModel = new GameModel();
    }

    public void setFieldsInRow(int row) {
        removeAll();
        buttons = new JButton[row][row];
        GridBagConstraints gbc = new GridBagConstraints();
        int buttonHeight = getParent().getHeight() / buttons.length + 1;
        int buttonWidht = getParent().getWidth() / buttons.length + 1;
        int counter = 0;
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                gbc.fill = GridBagConstraints.BOTH;
                gbc.gridx = j;
                gbc.gridy = i;
                gbc.weightx = 1;
                gbc.weighty = 1;
                JButton jButton = new JButton();
                buttons[i][j] = jButton;
                jButton.setMargin(new Insets(1, 1, 1, 1));
                jButton.setBackground(new Color(238, 238, 238));
                jButton.setText(String.valueOf(++counter));
                final int x = i;
                final int y = j;
                jButton.addActionListener((ActionEvent e) -> {
                    switch (context) {
                        case CHOOSE_START:
                            if (jButton.getBackground().equals(Color.GREEN)) {
                                jButton.setBackground(new Color(238, 238, 238));
                                gameModel.clearStart();
                            } else {
                                jButton.setBackground(Color.GREEN);
                                gameModel.setStart(x, y);
                            }
                            break;
                        case CHOOSE_END:
                            if (jButton.getBackground().equals(Color.ORANGE)) {
                                jButton.setBackground(new Color(238, 238, 238));
                                gameModel.clearEnd();
                            } else {
                                jButton.setBackground(Color.ORANGE);
                                gameModel.setEnd(x, y);
                            }
                            break;
                        case CHOOSE_WALL:
                            if (jButton.getBackground().equals(Color.RED)) {
                                jButton.setBackground(new Color(238, 238, 238));
                                gameModel.clearWall(x, y);
                            } else {
                                jButton.setBackground(Color.RED);
                                gameModel.setWall(x, y);
                            }
                            break;
                    }
                });
                jButton.setSize(buttonHeight, buttonWidht);
                add(jButton, gbc);

            }
            gameModel.setRows(row);
        }
        revalidate();
        repaint();
    }

    public void setContext(Context context) {
        this.context = context;
    }

    public void start() {
        try {
            List<Point> path = gameModel.start();
            for (Point point : path) {
                buttons[point.getY()][point.getX()].setBackground(Color.red);
            }
        } catch (Exception ex) {
            Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
